apiVersion: v1
kind: Service
metadata:
  name: agents-arq
  namespace: default
  labels:
    app: agents-arq
spec:
  type: NodePort      # NodePort para acceso desde minikube
  selector:
    app: agents-arq
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
